#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only

build() {
    add_binary "/usr/lib/dracut/modules.d/37composefs/composefs-pivot-sysroot" "/usr/bin/composefs-pivot-sysroot"
    add_runscript
}
