#!/bin/sh

set -eux

install_path="$1"

git clone https://github.com/systemd/systemd
(
	cd systemd
	git checkout v258
	meson setup _build
	ninja -C _build systemd-repart
	mkdir -p "${install_path}/src/shared"
	cp _build/systemd-repart "${install_path}"
	cp _build/src/shared/*.so "${install_path}/src/shared"
)

git clone https://github.com/tytso/e2fsprogs
(
	cd e2fsprogs
	git checkout v1.47.3
	./configure --disable-fuse2fs
	make -j$(nproc)
	cp misc/mke2fs "${install_path}/mkfs.ext4"
)
