#!/bin/sh

set -eux

os="${1:-fedora}"
cd "${0%/*}"

../common/check-config

case "${os}" in
    fedora)
        containerfile='Containerfile'
        cargo build --release --features=pre-6.15
        ;;
    arch)
        containerfile='Containerfile.arch'
        cargo build --release --features=pre-6.15
        ;;
    rhel9)
        containerfile='Containerfile.rhel9'
        cargo build --release --features=rhel9
        ;;
    ubuntu)
        containerfile='Containerfile.ubuntu'
        cargo build --release --features=pre-6.15
        ;;
    rawhide-compat)
        # try a variant with rawhide using the old mount APIs
        # this is currently failing due to a suspected kernel behaviour change
        # https://lore.kernel.org/linux-fsdevel/CAOYeF9WQhFDe+BGW=Dp5fK8oRy5AgZ6zokVyTj1Wp4EUiYgt4w@mail.gmail.com
        containerfile='Containerfile.rawhide'
        cargo build --release --features=pre-6.15
        ;;
    rawhide)
        containerfile='Containerfile.rawhide'
        cargo build --release --no-default-features --features=oci
        ;;
    *)
        echo "*** unknown variant ${os}"
        false
        ;;
esac

cp ../../target/release/cfsctl .
cp ../../target/release/composefs-setup-root extra/usr/lib/dracut/modules.d/37composefs/
CFSCTL='./cfsctl --repo tmp/sysroot/composefs'

rm -rf tmp
mkdir -p tmp/sysroot/composefs

podman build \
    --iidfile=tmp/base.iid \
    -f "${containerfile}" \
    .

BASE_ID="$(sed s/sha256:// tmp/base.iid)"

${CFSCTL} oci pull containers-storage:${BASE_ID}
${CFSCTL} oci prepare-boot "${BASE_ID}" --bootdir tmp/efi --cmdline console=ttyS0,115200 --entry-id=example --cmdline rw

../common/install-systemd-boot
../common/make-image "${os}-bls-efi.qcow2"
