#!/bin/sh

set -eux

os="${1:-fedora}"
cd "${0%/*}"

../common/check-config

if [ "${os}" != 'fedora' ]; then
    echo '*** only fedora is supported'
    false
fi

cargo build --release --features=pre-6.15

cp ../../target/release/cfsctl .
cp ../../target/release/composefs-setup-root extra/usr/lib/dracut/modules.d/37composefs/
CFSCTL='./cfsctl --repo tmp/sysroot/composefs'

rm -rf tmp
mkdir -p tmp/sysroot/composefs

# For debugging, add --no-cache to podman command
mkdir tmp/internal-sysroot
podman build \
    --iidfile=tmp/iid \
    -v $(pwd)/tmp/internal-sysroot:/tmp/sysroot:z,U \
    .

IMAGE_ID="$(sed s/sha256:// tmp/iid)"
podman save --format oci-archive -o tmp/final.tar "${IMAGE_ID}"
${CFSCTL} oci pull oci-archive:tmp/final.tar
IMAGE_FSVERITY="$(${CFSCTL} oci create-image "${IMAGE_ID}")"
fsck.erofs "tmp/sysroot/composefs/images/${IMAGE_FSVERITY}"

mkdir -p "tmp/sysroot/state/${IMAGE_FSVERITY}/etc/work"
mkdir -p "tmp/sysroot/state/${IMAGE_FSVERITY}/etc/upper"
mkdir -p "tmp/sysroot/state/${IMAGE_FSVERITY}/var"

mkdir -p tmp/efi/loader
echo 'timeout 3' > tmp/efi/loader/loader.conf
mkdir -p tmp/efi/EFI/BOOT tmp/efi/EFI/systemd
cp /usr/lib/systemd/boot/efi/systemd-bootx64.efi tmp/efi/EFI/systemd
cp /usr/lib/systemd/boot/efi/systemd-bootx64.efi tmp/efi/EFI/BOOT/BOOTX64.EFI
${CFSCTL} oci prepare-boot "${IMAGE_ID}" tmp/efi

../common/make-image fedora-unified-efi.qcow2
