FROM fedora:42 AS base
RUN --mount=type=cache,target=/var/cache/libdnf5 <<EOF
    set -eux

    dnf --setopt keepcache=1 install --allowerasing -y \
        btrfs-progs \
        composefs \
        dosfstools \
        kernel \
        policycoreutils-python-utils \
        openssh-server \
        selinux-policy-targeted \
        skopeo \
        strace \
        systemd \
        systemd-boot-unsigned \
        systemd-ukify \
        util-linux
EOF

# --- Everything above this line should hopefully stay cached ---

COPY cfsctl /usr/bin
COPY extra /
RUN <<EOF
    set -eux

    systemctl enable systemd-networkd

    checkmodule -M -m -o /etc/composefs_workarounds.mod /etc/composefs_workarounds.te
    semodule_package -o /etc/composefs_workarounds.pp -m /etc/composefs_workarounds.mod
    semodule -i /etc/composefs_workarounds.pp

    passwd -d root
    mkdir /sysroot
EOF

FROM base AS kernel
RUN --mount=type=bind,from=base,target=/mnt/base <<EOF
    set -eux

    mkdir -p /tmp/sysroot/composefs
    COMPOSEFS_FSVERITY="$(cfsctl --repo /tmp/sysroot compute-id --bootable /mnt/base)"

    mkdir -p /etc/kernel /etc/dracut.conf.d
    echo "console=ttyS0,115200 composefs=${COMPOSEFS_FSVERITY} rw" > /etc/kernel/cmdline
    kernel-install add-all
EOF

FROM base AS bootable
COPY --from=kernel /boot /boot
