//! Boot image management for OCI containers.
//!
//! A bootable EROFS image is a derived artifact from an OCI container image
//! that filters out some components (such as the UKI) to avoid circular references.

use std::collections::HashMap;
use std::sync::Arc;

use anyhow::Result;

use composefs::fsverity::FsVerityHashValue;
#[cfg(feature = "boot")]
use composefs::generic_tree::OciTransformOptions;
use composefs::generic_tree::XattrFiltering;
use composefs::repository::Repository;

use crate::OciDigest;

/// Generate a bootable EROFS image from a pulled OCI manifest (idempotent),
/// with configurable OCI transform options (currently just the xattr
/// filtering mode; see [`OciTransformOptions`]).
///
/// Each xattr filtering mode is cached independently under its own named
/// ref (see [`boot_image_for_mode`]): requesting a different mode for the
/// same manifest does not evict or overwrite the boot image cached for
/// another mode.
#[cfg(feature = "boot")]
pub fn generate_boot_image<ObjectID: FsVerityHashValue>(
    repo: &Arc<Repository<ObjectID>>,
    manifest_digest: &OciDigest,
    options: &OciTransformOptions,
) -> Result<ObjectID> {
    if let Some(existing) = boot_image_for_mode(repo, manifest_digest, options.xattrs)? {
        return Ok(existing);
    }

    let erofs_id =
        crate::ensure_oci_composefs_erofs_boot(repo, manifest_digest, None, None, options)?
            .expect("container image should produce boot EROFS");

    Ok(erofs_id)
}

/// Result of [`find_matching_boot_image`].
#[derive(Debug, Clone)]
pub enum BootImageMatch<ObjectID> {
    /// A mode produced the expected digest.
    Found {
        /// The xattr filtering mode that produced `digest`.
        mode: XattrFiltering,
        /// The resulting boot image digest, equal to the `expected`
        /// argument passed to [`find_matching_boot_image`].
        digest: ObjectID,
    },
    /// No mode matched. Contains every `(mode, computed_digest)` pair that
    /// was tried, in the order tried, for use in error messages.
    NotFound(Vec<(XattrFiltering, ObjectID)>),
}

/// Try each [`XattrFiltering`] mode (generating, or cache-hitting, the boot
/// image for each) until one produces a boot image whose digest matches
/// `expected`. Short-circuits on the first match.
///
/// This is intended for callers that have an expected boot image digest
/// (e.g. parsed from a UKI's embedded kernel cmdline) and need to determine
/// which xattr filtering mode was used to originally produce it, without
/// hard-coding knowledge of which modes exist. This can happen when a boot
/// image is regenerated by a different composefs-rs version than the one
/// that originally produced it, since the default xattr filtering mode has
/// changed over time.
///
/// On success, returns the matching mode and digest (the digest is always
/// equal to `expected`, but is included for caller convenience). On
/// failure, returns every `(mode, digest)` pair that was attempted, so the
/// caller can build an informative error message listing what was tried.
#[cfg(feature = "boot")]
pub fn find_matching_boot_image<ObjectID: FsVerityHashValue>(
    repo: &Arc<Repository<ObjectID>>,
    manifest_digest: &OciDigest,
    expected: &ObjectID,
) -> Result<BootImageMatch<ObjectID>> {
    let mut tried = Vec::with_capacity(XattrFiltering::VARIANTS.len());

    for &mode in XattrFiltering::VARIANTS {
        let options = OciTransformOptions { xattrs: mode };
        let digest = generate_boot_image(repo, manifest_digest, &options)?;
        if &digest == expected {
            return Ok(BootImageMatch::Found { mode, digest });
        }
        tried.push((mode, digest));
    }

    Ok(BootImageMatch::NotFound(tried))
}

/// Returns the boot EROFS image verity built with the default
/// ([`XattrFiltering::AllowlistOnly`]) xattr filtering mode, if one exists.
pub fn boot_image<ObjectID: FsVerityHashValue>(
    repo: &Repository<ObjectID>,
    manifest_digest: &OciDigest,
) -> Result<Option<ObjectID>> {
    boot_image_for_mode(repo, manifest_digest, XattrFiltering::AllowlistOnly)
}

/// Returns the boot EROFS image verity built with the given xattr filtering
/// `mode`, if one exists.
pub fn boot_image_for_mode<ObjectID: FsVerityHashValue>(
    repo: &Repository<ObjectID>,
    manifest_digest: &OciDigest,
    mode: XattrFiltering,
) -> Result<Option<ObjectID>> {
    crate::composefs_boot_erofs_for_manifest(
        repo,
        manifest_digest,
        None,
        repo.erofs_version(),
        mode,
    )
}

/// Remove all bootable EROFS image references (idempotent), across every
/// xattr filtering mode that has been cached for this manifest.
///
/// The EROFS images themselves are garbage-collected on the next `repo.gc()`.
pub fn remove_boot_image<ObjectID: FsVerityHashValue>(
    repo: &Arc<Repository<ObjectID>>,
    manifest_digest: &OciDigest,
) -> Result<()> {
    let img = crate::oci_image::OciImage::open(repo, manifest_digest, None)?;

    if !img.is_container_image() {
        anyhow::bail!("not a container image");
    }

    if img.boot_image_refs().is_empty() {
        return Ok(());
    }

    // Read original config JSON to preserve its exact bytes
    let config_json = img.read_config_json(repo)?;

    let (_config_digest, new_config_verity) = crate::write_config_raw(
        repo,
        &config_json,
        img.layer_refs().clone(),
        img.image_ref_v2(), // preserve existing V2 image ref
        img.image_ref_v1(), // preserve existing V1 image ref
        &HashMap::new(),    // drop all boot images, every mode
    )?;

    let manifest_json = img.read_manifest_json(repo)?;
    let layer_verities: Vec<_> = img
        .layer_refs()
        .iter()
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect();

    crate::oci_image::rewrite_manifest(
        repo,
        &manifest_json,
        manifest_digest,
        &new_config_verity,
        &layer_verities,
        None,
    )?;

    Ok(())
}

#[cfg(all(test, feature = "boot"))]
mod test {
    use super::*;
    use composefs::fsverity::Sha256HashValue;
    use composefs::test::TestRepo;
    use composefs_boot::bootloader::get_boot_resources;

    use crate::oci_image::OciImage;
    use crate::test_util;

    #[tokio::test]
    async fn test_boot_image_none_before_generate() {
        let test_repo = TestRepo::<Sha256HashValue>::new();
        let repo = &test_repo.repo;

        let img = test_util::create_bootable_image(repo, Some("myapp:v1"), 1).await;

        let result = boot_image(repo, &img.manifest_digest).unwrap();
        assert!(result.is_none(), "no boot image should exist yet");
    }

    #[tokio::test]
    async fn test_generate_boot_image() {
        let test_repo = TestRepo::<Sha256HashValue>::new();
        let repo = &test_repo.repo;

        let img = test_util::create_bootable_image(repo, Some("myapp:v1"), 1).await;

        let image_verity =
            generate_boot_image(repo, &img.manifest_digest, &OciTransformOptions::default())
                .unwrap();

        let found = boot_image(repo, &img.manifest_digest).unwrap();
        assert_eq!(found, Some(image_verity.clone()));

        // Open by tag since manifest was rewritten
        let oci = OciImage::open_ref(repo, "myapp:v1").unwrap();
        assert_eq!(
            oci.boot_image_ref(repo.erofs_version()),
            Some(&image_verity)
        );

        let plain_image = crate::image::create_filesystem(
            repo,
            &img.config_digest,
            None,
            &OciTransformOptions::default(),
        )
        .unwrap();
        let plain_verity = plain_image.compute_image_id(repo.erofs_version());
        assert_ne!(
            image_verity, plain_verity,
            "boot-transformed image should differ from non-transformed image"
        );
    }

    #[tokio::test]
    async fn test_generate_boot_image_idempotent() {
        let test_repo = TestRepo::<Sha256HashValue>::new();
        let repo = &test_repo.repo;

        let img = test_util::create_bootable_image(repo, Some("myapp:v1"), 1).await;

        let v1 = generate_boot_image(repo, &img.manifest_digest, &OciTransformOptions::default())
            .unwrap();
        let v2 = generate_boot_image(repo, &img.manifest_digest, &OciTransformOptions::default())
            .unwrap();
        assert_eq!(v1, v2);
    }

    /// Each xattr filtering mode is cached under its own named ref: generating
    /// `KeepUserXattrs` produces a distinct image from the default
    /// `AllowlistOnly` mode (when a `user.*` xattr is present), and neither
    /// mode evicts or overwrites the other's cache entry.
    #[tokio::test]
    async fn test_generate_boot_image_modes_cache_independently() {
        use test_util::{KernelVersion, OsImage};

        let test_repo = TestRepo::<Sha256HashValue>::new();
        let repo = &test_repo.repo;

        let img = OsImage::bootable(KernelVersion::V1)
            .with_layer("/usr/lib/testfile 5 100644 1 0 0 0 0.0 - hello - user.testattr=hi")
            .build_oci(repo, Some("myapp:v1"))
            .await;

        let allowlist_id = generate_boot_image(
            repo,
            &img.manifest_digest,
            &OciTransformOptions {
                xattrs: XattrFiltering::AllowlistOnly,
            },
        )
        .unwrap();

        let keep_user_id = generate_boot_image(
            repo,
            &img.manifest_digest,
            &OciTransformOptions {
                xattrs: XattrFiltering::KeepUserXattrs,
            },
        )
        .unwrap();

        assert_ne!(
            allowlist_id, keep_user_id,
            "KeepUserXattrs should produce a distinct image from AllowlistOnly \
             when a user.* xattr is present"
        );

        // Both modes remain independently cached: neither generation call
        // above evicted the other mode's entry.
        assert_eq!(
            boot_image(repo, &img.manifest_digest).unwrap(),
            Some(allowlist_id.clone()),
            "AllowlistOnly cache entry should be unaffected by the KeepUserXattrs call"
        );
        assert_eq!(
            boot_image_for_mode(repo, &img.manifest_digest, XattrFiltering::KeepUserXattrs)
                .unwrap(),
            Some(keep_user_id.clone())
        );

        // Re-generating either mode is a cache hit, returning the same image.
        let allowlist_cached =
            generate_boot_image(repo, &img.manifest_digest, &OciTransformOptions::default())
                .unwrap();
        assert_eq!(allowlist_cached, allowlist_id);
        let keep_user_cached = generate_boot_image(
            repo,
            &img.manifest_digest,
            &OciTransformOptions {
                xattrs: XattrFiltering::KeepUserXattrs,
            },
        )
        .unwrap();
        assert_eq!(keep_user_cached, keep_user_id);
    }

    #[tokio::test]
    async fn test_remove_boot_image() {
        let test_repo = TestRepo::<Sha256HashValue>::new();
        let repo = &test_repo.repo;

        let img = test_util::create_bootable_image(repo, Some("myapp:v1"), 1).await;

        generate_boot_image(repo, &img.manifest_digest, &OciTransformOptions::default()).unwrap();
        assert!(boot_image(repo, &img.manifest_digest).unwrap().is_some());

        remove_boot_image(repo, &img.manifest_digest).unwrap();
        assert!(
            boot_image(repo, &img.manifest_digest).unwrap().is_none(),
            "boot image should be gone after remove"
        );

        let oci = OciImage::open_ref(repo, "myapp:v1").unwrap();
        assert!(oci.is_container_image());

        let gc = repo.gc(&[]).unwrap();
        assert_eq!(
            gc.images_pruned, 1,
            "exactly the EROFS image should be pruned"
        );
    }

    #[tokio::test]
    async fn test_remove_boot_image_idempotent() {
        let test_repo = TestRepo::<Sha256HashValue>::new();
        let repo = &test_repo.repo;

        let img = test_util::create_bootable_image(repo, Some("myapp:v1"), 1).await;

        remove_boot_image(repo, &img.manifest_digest).unwrap();

        generate_boot_image(repo, &img.manifest_digest, &OciTransformOptions::default()).unwrap();
        remove_boot_image(repo, &img.manifest_digest).unwrap();
        remove_boot_image(repo, &img.manifest_digest).unwrap();

        assert!(boot_image(repo, &img.manifest_digest).unwrap().is_none());
    }

    #[tokio::test]
    async fn test_remove_boot_image_clears_all_modes() {
        let test_repo = TestRepo::<Sha256HashValue>::new();
        let repo = &test_repo.repo;

        let img = test_util::create_bootable_image(repo, Some("myapp:v1"), 1).await;

        generate_boot_image(
            repo,
            &img.manifest_digest,
            &OciTransformOptions {
                xattrs: XattrFiltering::AllowlistOnly,
            },
        )
        .unwrap();
        generate_boot_image(
            repo,
            &img.manifest_digest,
            &OciTransformOptions {
                xattrs: XattrFiltering::KeepUserXattrs,
            },
        )
        .unwrap();

        remove_boot_image(repo, &img.manifest_digest).unwrap();

        assert!(boot_image(repo, &img.manifest_digest).unwrap().is_none());
        assert!(
            boot_image_for_mode(repo, &img.manifest_digest, XattrFiltering::KeepUserXattrs)
                .unwrap()
                .is_none()
        );
    }

    /// When both xattr filtering modes are cached simultaneously for a
    /// tagged manifest, GC must keep both EROFS images alive; once untagged,
    /// GC must collect both.
    #[tokio::test]
    async fn test_boot_image_gc_handles_both_modes_simultaneously() {
        use test_util::{KernelVersion, OsImage};

        let test_repo = TestRepo::<Sha256HashValue>::new();
        let repo = &test_repo.repo;

        let img = OsImage::bootable(KernelVersion::V1)
            .with_layer("/usr/lib/testfile 5 100644 1 0 0 0 0.0 - hello - user.testattr=hi")
            .build_oci(repo, Some("myapp:v1"))
            .await;

        let allowlist_id = generate_boot_image(
            repo,
            &img.manifest_digest,
            &OciTransformOptions {
                xattrs: XattrFiltering::AllowlistOnly,
            },
        )
        .unwrap();
        let keep_user_id = generate_boot_image(
            repo,
            &img.manifest_digest,
            &OciTransformOptions {
                xattrs: XattrFiltering::KeepUserXattrs,
            },
        )
        .unwrap();
        assert_ne!(allowlist_id, keep_user_id);

        // Both modes' images must survive GC while tagged.
        let gc = repo.gc(&[]).unwrap();
        assert_eq!(gc.images_pruned, 0);
        assert_eq!(gc.streams_pruned, 0);

        let oci = OciImage::open_ref(repo, "myapp:v1").unwrap();
        assert_eq!(
            oci.boot_image_ref(repo.erofs_version()),
            Some(&allowlist_id)
        );
        assert_eq!(
            oci.boot_image_ref_for_mode(repo.erofs_version(), XattrFiltering::KeepUserXattrs),
            Some(&keep_user_id)
        );

        // Once untagged, GC must collect both EROFS images.
        crate::oci_image::untag_image(repo, "myapp:v1").unwrap();
        let gc = repo.gc(&[]).unwrap();
        assert_eq!(
            gc.images_pruned, 2,
            "both the AllowlistOnly and KeepUserXattrs boot images should be pruned"
        );
    }

    #[tokio::test]
    async fn test_boot_image_gc_preserves_when_tagged() {
        let test_repo = TestRepo::<Sha256HashValue>::new();
        let repo = &test_repo.repo;

        let img = test_util::create_bootable_image(repo, Some("myapp:v1"), 1).await;

        let image_verity =
            generate_boot_image(repo, &img.manifest_digest, &OciTransformOptions::default())
                .unwrap();

        let gc = repo.gc(&[]).unwrap();
        assert_eq!(gc.images_pruned, 0);
        assert_eq!(gc.streams_pruned, 0);

        let oci = OciImage::open_ref(repo, "myapp:v1").unwrap();
        assert_eq!(
            oci.boot_image_ref(repo.erofs_version()),
            Some(&image_verity)
        );
    }

    #[tokio::test]
    async fn test_boot_image_gc_collects_after_untag() {
        let test_repo = TestRepo::<Sha256HashValue>::new();
        let repo = &test_repo.repo;

        let img = test_util::create_bootable_image(repo, Some("myapp:v1"), 1).await;

        generate_boot_image(repo, &img.manifest_digest, &OciTransformOptions::default()).unwrap();

        crate::oci_image::untag_image(repo, "myapp:v1").unwrap();

        let gc = repo.gc(&[]).unwrap();
        assert!(gc.objects_removed > 0);
        assert_eq!(gc.images_pruned, 1);
        assert!(gc.streams_pruned > 0);

        let gc2 = repo.gc(&[]).unwrap();
        assert_eq!(gc2.objects_removed, 0);
        assert_eq!(gc2.images_pruned, 0);
        assert_eq!(gc2.streams_pruned, 0);
    }

    #[tokio::test]
    async fn test_remove_boot_image_then_gc_preserves_oci() {
        let test_repo = TestRepo::<Sha256HashValue>::new();
        let repo = &test_repo.repo;

        let img = test_util::create_bootable_image(repo, Some("myapp:v1"), 1).await;

        generate_boot_image(repo, &img.manifest_digest, &OciTransformOptions::default()).unwrap();

        remove_boot_image(repo, &img.manifest_digest).unwrap();
        let gc = repo.gc(&[]).unwrap();
        assert_eq!(gc.images_pruned, 1);

        let oci = OciImage::open_ref(repo, "myapp:v1").unwrap();
        assert!(oci.is_container_image());
        assert!(oci.boot_image_ref(repo.erofs_version()).is_none());
    }

    /// [`find_matching_boot_image`] finds the default ([`XattrFiltering::AllowlistOnly`])
    /// mode when `expected` is the digest that mode produces, without
    /// needing to try any other mode.
    #[tokio::test]
    async fn test_find_matching_boot_image_default_mode() {
        let test_repo = TestRepo::<Sha256HashValue>::new();
        let repo = &test_repo.repo;

        let img = test_util::create_bootable_image(repo, Some("myapp:v1"), 1).await;

        let allowlist_id = generate_boot_image(
            repo,
            &img.manifest_digest,
            &OciTransformOptions {
                xattrs: XattrFiltering::AllowlistOnly,
            },
        )
        .unwrap();

        let result = find_matching_boot_image(repo, &img.manifest_digest, &allowlist_id).unwrap();
        assert!(matches!(
            result,
            BootImageMatch::Found {
                mode: XattrFiltering::AllowlistOnly,
                digest,
            } if digest == allowlist_id
        ));
    }

    /// [`find_matching_boot_image`] finds [`XattrFiltering::KeepUserXattrs`]
    /// when `expected` is the digest that mode produces, proving it actually
    /// tries every mode rather than stopping after the default.
    #[tokio::test]
    async fn test_find_matching_boot_image_non_default_mode() {
        use test_util::{KernelVersion, OsImage};

        let test_repo = TestRepo::<Sha256HashValue>::new();
        let repo = &test_repo.repo;

        let img = OsImage::bootable(KernelVersion::V1)
            .with_layer("/usr/lib/testfile 5 100644 1 0 0 0 0.0 - hello - user.testattr=hi")
            .build_oci(repo, Some("myapp:v1"))
            .await;

        let keep_user_id = generate_boot_image(
            repo,
            &img.manifest_digest,
            &OciTransformOptions {
                xattrs: XattrFiltering::KeepUserXattrs,
            },
        )
        .unwrap();

        let result = find_matching_boot_image(repo, &img.manifest_digest, &keep_user_id).unwrap();
        assert!(matches!(
            result,
            BootImageMatch::Found {
                mode: XattrFiltering::KeepUserXattrs,
                digest,
            } if digest == keep_user_id
        ));
    }

    /// [`find_matching_boot_image`] returns `NotFound` with every attempted
    /// `(mode, digest)` pair when `expected` matches no mode.
    #[tokio::test]
    async fn test_find_matching_boot_image_not_found() {
        let test_repo = TestRepo::<Sha256HashValue>::new();
        let repo = &test_repo.repo;

        let img = test_util::create_bootable_image(repo, Some("myapp:v1"), 1).await;
        let bogus = Sha256HashValue::from_hex("ff".repeat(32)).unwrap();

        let result = find_matching_boot_image(repo, &img.manifest_digest, &bogus).unwrap();
        let BootImageMatch::NotFound(tried) = result else {
            panic!("expected NotFound, got a match");
        };
        assert_eq!(tried.len(), XattrFiltering::VARIANTS.len());
        assert_eq!(
            tried.iter().map(|(mode, _)| *mode).collect::<Vec<_>>(),
            XattrFiltering::VARIANTS
        );
        for (_, digest) in &tried {
            assert_ne!(*digest, bogus);
        }
    }

    /// Boot EROFS differs from plain EROFS and contains the expected boot entries.
    #[tokio::test]
    async fn test_boot_content() {
        for tag in ["myapp:v1", "uki:v1"] {
            let test_repo = TestRepo::<Sha256HashValue>::new();
            let repo = &test_repo.repo;

            let img = test_util::create_bootable_image(repo, Some(tag), 1).await;

            let boot_verity =
                generate_boot_image(repo, &img.manifest_digest, &OciTransformOptions::default())
                    .unwrap();

            let fs = crate::image::create_filesystem(
                repo,
                &img.config_digest,
                None,
                &OciTransformOptions::default(),
            )
            .unwrap();
            let boot_entries = get_boot_resources(&fs, repo).unwrap();
            assert_eq!(boot_entries.len(), 2, "tag={tag}");
            assert!(
                boot_entries.iter().any(|e| matches!(
                    e,
                    composefs_boot::bootloader::BootEntry::UsrLibModulesVmLinuz(_)
                )),
                "tag={tag}: expected vmlinuz entry"
            );
            assert!(
                boot_entries
                    .iter()
                    .any(|e| matches!(e, composefs_boot::bootloader::BootEntry::Type2(_))),
                "tag={tag}: expected Type2 entry"
            );

            let plain_fs = crate::image::create_filesystem(
                repo,
                &img.config_digest,
                None,
                &OciTransformOptions::default(),
            )
            .unwrap();
            let plain_verity = plain_fs.commit_image(repo, None).unwrap();
            assert_ne!(boot_verity, plain_verity, "tag={tag}");
        }
    }
}
