name: publish
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-22.04
    environment: crates.io
    permissions: {}
    timeout-minutes: 20
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - run: cargo publish -p composefs
      - run: cargo publish -p composefs-oci
      - run: cargo publish -p composefs-boot
      - run: cargo publish -p cfsctl
      - run: cargo publish -p composefs-setup-root
